language: python

python:
  - '2.6'

before_script:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "pip install --upgrade https://github.com/mitsuhiko/flask/tarball/master"
  - "flask --app=flaskr initdb"
  - "flask --app=flaskr run &"

script:
  - "py.test test/test_flaskr.py"
  - "py.test test/test_pyorg.py"
